### ISSUE TITLE
Incorrect table column width calculcations with colorized strings

### ISSUE THREAD

**Issue by schlessera** [wp-cli/php-cli-tools#106]
The column widths in a formatted table are incorrectly calculated when the strings have been ran through `WP_CLI::colorize()` before.

<img width="306" alt="screenshot 2017-06-27 11 44 27" src="https://user-images.githubusercontent.com/83631/27581843-2f2cdc68-5b2f-11e7-90df-1f3040cae3c7.png">

According to https://github.com/wp-cli/php-cli-tools/pull/69, this should be fixed, so there might have been a regression in meantime.

**Comment by danielbachhuber** [comment]
Fixed in #111
