### ISSUE TITLE
The returned value of `--format=count` needs line break?

### ISSUE THREAD

**Issue by miya0001** [wp-cli/php-cli-tools#119]
There is no line break. Is this problem which should be fixed?
Are there any backward compatibility issues?

```
[miya@localhost wp-cli (master *)]$ wp user list --format=count
1[miya@localhost wp-cli (master *)]$ 
```

For example, the result of the `jq` has a line break.
```
$ wp user list --format=json | jq length
1
```

**Comment by danielbachhuber** [comment]
> Is this problem which should be fixed?

I don't think so, no. Not having a line break makes it easier to use the output in some other system.
