### ISSUE TITLE
Feature Request:  Horizontal Rule

### ISSUE THREAD

**Issue by DarkAxi0m** [wp-cli/php-cli-tools#133]
Just a thought, but it would be handy to have something like HTML's `<hr/>`
e.g. `cli\hr($msg)`

>  'MESSAGE STRING'
>  '-----------------------------------------'

**Comment by schlessera** [comment]
Thanks for the request, @DarkAxi0m !

However, I don't think this is something that should be part of the library, as in general, decorative elements like this cause more harm than good. They don't properly adapt if they change the screen size, and serve no actual purpose.

I'll close this request, but in case you need this for your own purpose, you can easily build it yourself like this:
```
$msg = 'Some kind of message';
cli\line( $msg );
cli\line( str_repeat( '-', strlen( $msg ) ) );
```
