### ISSUE TITLE
setRenderer doesn't work

### ISSUE THREAD

**Issue by joerecra** [wp-cli/php-cli-tools#135]
When I use: $table->setRenderer(new \cli\table\Ascii([80, 20, 20])) or I change array values into Ascii this doesn't work, table doesn't rendered. 

$table = new \cli\Table();
$table->setHeaders($headers);
$table->setRows($results);
$table->setRenderer(new \cli\table\Ascii([80, 20, 20]));
$table->display();

Please any help I pleasure it.

![captura](https://user-images.githubusercontent.com/11606218/44410227-93feed80-a529-11e8-9ad4-883805f1c32a.png)

**Comment by wojsmol** [comment]
Please post `wp --info` from your testing environment.

**Comment by joerecra** [comment]
Well @schlessera, Whit this: new \cli\table\Ascii([80, 20, 20]) I'm trying to set width columns in my table.

When I add one column "Empty" and remove setRenderer this automatically renderers, let's call it "good"

![tablegood](https://user-images.githubusercontent.com/11606218/44416999-12638b80-a53a-11e8-9d74-558a490067bc.png)

But I want to set width, putting my own widths Maybe 50 or 80 or 100 whatever, I don't Know. But this doesn't work.

In last image I used: $table->setRenderer(new \cli\table\Ascii([80, 5, 20, 20, 20])); 
but nothing changes. Another thing, in examples dir I change widths and it doesn't work neither.

I'm confusing. Sorry

**Comment by joerecra** [comment]
Thank you @schlessera bug was corrected !
