### ISSUE TITLE
Installation instructions?

### ISSUE THREAD

**Issue by dahousecat** [wp-cli/php-cli-tools#138]
How do I install this?

Where should these files be put?

I tried just sticking them in the plugins dir:

`require_once(WP_PLUGIN_DIR . '/php-cli-tools/lib/cli/cli.php');`

but this results in an error `Cannot redeclare cli\render()`.

I'm not using composer on my project - is composer a requirement for using php-cli-tools?

**Comment by swissspidy** [comment]
What exactly are you trying to achieve?

If you want to write a custom WP-CLI command, you don't need php-cli-tools.

And yes, ideally you'd use composer to install this package.

Please note that Github issues aren't for general support questions, but there are other venues you can try: http://wp-cli.org/#support. It's probably easiest if you'd join the Slack channel so we could sort this out.

**Comment by schlessera** [comment]
@dahousecat Please join us in make.wordpress.org Slack team in the #cli team if you have further questions about this. As @swissspidy has stated, GitHub is not the right venue for support.
