### ISSUE TITLE
Uncaught TypeError: join(): Argument #2 ($array) must be of type ?array, string given

### ISSUE THREAD

**Issue by OzzyCzech** [wp-cli/php-cli-tools#143]
## Uncaught TypeError: join(): Argument `#2` ($array) must be of type ?array, string given

You can reproduce that error under PHP 8 with example code:

```
php examples/arguments.php --help
```

There is pull request already #142 from @oytuntez

**Comment by OzzyCzech** [comment]
Thanks @schlessera for merging #142

**Comment by schlessera** [comment]
@OzzyCzech I pushed a release, in case you need one: https://github.com/wp-cli/php-cli-tools/releases/tag/v0.11.12
