### ISSUE TITLE
Prompting doesn't support arrow keys

### ISSUE THREAD

**Issue by rodrigoprimo** [wp-cli/php-cli-tools#72]
From: https://github.com/wp-cli/wp-cli/issues/996

Prompting doesn't support arrow keys because php-cli-tools uses fgets(STDIN) instead of readline:

https://github.com/wp-cli/php-cli-tools/blob/master/lib/cli/Streams.php#L130

The following seem to fix this issue:

```
diff --git a/lib/cli/Streams.php b/lib/cli/Streams.php
index b750636..081a6bd 100755
--- a/lib/cli/Streams.php
+++ b/lib/cli/Streams.php
@@ -126,6 +126,8 @@ class Streams {
 
                if( $format ) {
                        fscanf( static::$in, $format . "\n", $line );
+               } else if ( function_exists( 'readline' ) ) {
+                       $line = readline();
                } else {
                        $line = fgets( static::$in );
                }
```

But, at least for wp-cli `--prompt` parameter, another problem is created. If you use the left arrow to go to the beginning of what you typed, the cursor goes to the beginning of the line, before the question presented to the user. I think this happens because readline() expects the question as a parameter. So we will need to change that as well.

**Comment by danielbachhuber** [comment]
I'm switching to `readline()` in WP-CLI for this — don't think it needs to be fixed in php-cli-tools.
