### ISSUE TITLE
% characters not properly escaped before being passed to sprintf()

### ISSUE THREAD

**Issue by leewillis77** [wp-cli/php-cli-tools#86]
Using WP CLI, the following steps show the problem:

* Update your user account so that your name contains a %, e.g. "Lee %s Willis"
* Run wp user list
* Expected output:
```
+----+-------------+---------------+---------------------+---------------------+---------------+
| ID | user_login  | display_name  | user_email          | user_registered     | roles         |
+----+-------------+---------------+---------------------+---------------------+---------------+
| 5  | leewillis77 | Lee %s Willis | lee@example.com | 2015-07-19 15:11:01 | subscriber    |
```

* Actual output
```
+----+-------------+---------------+---------------------+---------------------+---------------+
| ID | user_login  | display_name  | user_email          | user_registered     | roles         |
+----+-------------+---------------+---------------------+---------------------+---------------+
| 5  | leewillis77 | Lee  Willis | lee@example.com | 2015-07-19 15:11:01 | subscriber    |
```

* Note that the name of the user is displayed as "Lee Willis".

The %s has not been escaped and has been passed to sprintf as-is. There is code already in place that looks like it tries to handle this, but it doesn't. 

PR to follow that simplifies the escaping (and resolves this issue), obviously it'll need review to see why the original wasn't this straightforward.

**Comment by leewillis77** [comment]
So; 

I've just looked at this again in an attempt to provide test cases that work. I was confused for quite some time by a bug in the test framework (Separate PR that fixes that). However - even with that I can't get working tests. The change that works for WP-CLI doesn't produce a working test case. There are no sprintf warnings, but the % characters are getting dropped still. 

My guess is that something is applying during the phpunit run that doesn't apply when WP-CLI is running. I think I've narrowed the issue to Streams.php L#41 where the output is passed through Colors::colorize() which seems to swallow single % characters. I'm not anywhere familiar enough to start working out how / if this should be escaped - so any other advice welcome. 

This PR is up to date with my original proposed fix, and the unit test that should prove it - however it's currently failing as the %s get swallowed when the test is run - albeit this patch *does* fix my original WP-CLI issue.

**Comment by danielbachhuber** [comment]
@leewillis77 Sorry for the late response here, slipped off my radar.

I think the problem is actually #90 — when isTTY is false, `Colors::colorize()` strips `%` characters when it shouldn't. This code has been in here for a while 039e2ec9fb44b8c7dd77e6afe2b26be866d99e29

I don't have a great suggestion on a fix at the moment. @tollmanz last touched this file in 5a0138cdc0bbe50ac1c7a79cd11d6366412707f3 — maybe he has a suggestion?

**Comment by danielbachhuber** [comment]
Hm. What if `preg_replace()` ignored `%s` and `%d` ?

**Comment by Korri** [comment]
Maybe cycling through colors instead of using a regex, might be a little slower, but it would not create unexpected behaviors.
