### ISSUE TITLE
Colors::colorize removes sprintf flags on windows

### ISSUE THREAD

**Issue by Korri** [wp-cli/php-cli-tools#90]
I'm using the script on windows, and `shouldColorize` returns `false`, so the following lines strips all sprintf flags:
```php
$return = preg_replace('/%((%)|.)/', '$2', $string);
```

Causes `cli\menu()` to show a list of dots instead of the choices.

**Comment by danielbachhuber** [comment]
> I'm using the script on windows, and shouldColorize returns false

Hm. Do you have a suggested fix?

**Comment by Korri** [comment]
I'll comment on #86 as the discution seem to be going on there.

**Comment by danielbachhuber** [comment]
@Korri Can you verify the fix in #91 ?

**Comment by Korri** [comment]
Works like a charm !

**Comment by danielbachhuber** [comment]
:+1:
