### ISSUE TITLE
Use HTML-like syntax instead of own custom one

### ISSUE THREAD

**Issue by nazar-pc** [wp-cli/php-cli-tools#96]
What I mean is to replace:

```
%ySomething yellow%n
```

with:

```
<y>Something yellow</y>
```

Benefits:
- easier and more familiar to read, since there is no `ySomething` and similar things, at the end of the day we are all well trained to read HTML:)
- IDE usually supports HTML within string literals, so it will be:
  - automatically highlighted
  - possible to fold blocks of text
  - working with autocomplete of closing such "tags"
  - working with spellchecking
  - so on...
- there are numerous HTML parsers that can be used to pre/post-process such strings or strip HTML tags from string

I've implemented such approach in very basic form here: https://github.com/nazar-pc/phpt-tests-runner/blob/master/bin/phpt-tests-runner#L284
Even GitHub is capable to automatically highlight it in a basic form :smile:

**Comment by danielbachhuber** [comment]
How would you handle backwards compatibility concerns (e.g. someone who has already used `<y>` in a string)?

**Comment by nazar-pc** [comment]
I would not worry about this too much because of 2 reasons:
1. Not very probable, honestly
2. While project is not at 1.x yet, minor releases might break backward compatibility, especially only partially and if they are beneficial for project's future (this is in case if you follow semantic versioning); it would be much harder to change something like this after 1.0

Just make sure that loud enough statement is added to release notes (also current syntax might be still supported for few releases to ensure smooth upgrade process).

**Comment by nazar-pc** [comment]
@danielbachhuber, do you (or maybe other maintainers) have any other objections or comments?

**Comment by danielbachhuber** [comment]
> do you (or maybe other maintainers) have any other objections or comments?

I don't think the benefit is worth the backwards compatibility break.

**Comment by nazar-pc** [comment]
It might be complementary syntax for a while to see if users really like it (I'm pretty sure they will), which wouldn't be a backwards compatibility break until (and if) you decide to drop current syntax.

**Comment by nazar-pc** [comment]
Example of implementation in #100, PTAL

**Comment by Luxian** [comment]
+1 for this feature. It will be way more easier to read and write.

**Comment by nazar-pc** [comment]
Could you give some explanation why? No discussion in months and now suddenly it is closed.

**Comment by danielbachhuber** [comment]
> Could you give some explanation why?

Sure — it's not a change I want to implement. You're welcome to fork and implement in your own version.
